import { Metadata } from 'next';
import Link from 'next/link';
import { getTodo, Todo } from '@/lib/todos';

type Params = {
  params: { todoId: string };
};

export const revalidate = 5;

// export const metadata: Metadata = {
//   title: {
//     default: 'Todo',
//     template: '%s | ToDo',
//   },
//   description: 'Generated by create next app',
// };

export async function generateMetadata({
  params: { todoId },
}: Params): Promise<Metadata> {
  const todo: Todo = await getTodo(+todoId);
  return {
    title: `Todo - ${todo.title}`,
  };
}

export default async function TodoPage({ params: { todoId } }: Params) {
  const { title, completed } = await getTodo(+todoId);
  console.log('todos/todo>>', todoId);
  if (!title) {
    // return <h1 className='text-2xl text-red-500'>#{todoId} is not found!!</h1>;
    throw new Error(`#${todoId} is not found!!`);
  }

  return (
    <div className='text-left'>
      <div>id: {todoId}</div>
      <div>title: {title}</div>
      <div>completed: {completed ? 'Done' : 'Doing...'}</div>
      <Link href='/todos'>Go List</Link>
    </div>
  );
}
